# Generated by Django 4.1.7 on 2023-02-21 09:27

from django.db import migrations, models

import stripe_payment_app.validators


class Migration(migrations.Migration):
    dependencies = [
        (
            "stripe_payment_app",
            "0003_discount_tax_alter_order_options_order_discount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("rub", "рублей"), ("usd", "долларов")],
                default="rub",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="percent_off",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[stripe_payment_app.validators.is_positive],
                verbose_name="Скидка",
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="percentage",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=6,
                validators=[stripe_payment_app.validators.is_positive],
                verbose_name="Налоговая ставка",
            ),
        ),
    ]
